//
//  main.swift
//  SBEnumerator
//
//  Created by Alex da Franca on 27.05.18.
//  Copyright © 2018 Farbflash. All rights reserved.
//

import Foundation

let options = CliArguments()

if options.help {
    options.printHelpText()
    exit(EXIT_SUCCESS)
}
if options.version {
    options.printVersion()
    exit(EXIT_SUCCESS)
}

guard !options.paths.isEmpty else {
        writeToStdError("Expected path to an XML file!\n")
        options.printHelpText()
        exit(EXIT_FAILURE)
}

let storyBoardParser = StoryboardParserDelegate()

for storyboardFile in options.paths {
    let url = URL(fileURLWithPath: storyboardFile)
    guard let parser = XMLParser(contentsOf: url) else {
        writeToStdError("Unable to read xml file at \(url.absoluteString)!\n")
        continue
    }
    parser.delegate = storyBoardParser
    parser.parse()
}

var filecontents = """
//
// StoryboardIdentifiers.swift
// Automatically created by SBEnumerator.
//
// DO NOT EDIT THIS FILE!
// This file was automatically generated from the contents of storyboard files
// Update the storyboard and then use the SBEnumerator
// to create the corresponding Enum source files automatically

import Foundation

struct StoryboardIdentifiers {

\(storyBoardParser.tvCellIdentifiersEnum(blockIndent: "    "))

\(storyBoardParser.cvCellIdentifiersEnum(blockIndent: "    "))

\(storyBoardParser.aiCellIdentifiersEnum(blockIndent: "    "))
}
"""

writeToStdOut(filecontents)

exit(EXIT_SUCCESS)
